# Generated by Django 3.0.3 on 2020-02-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Torrents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('magnet', models.TextField()),
                ('type', models.CharField(choices=[('to', 'Torrent')], default=[('to', 'Torrent')], max_length=2)),
            ],
        ),
    ]
