# Generated by Django 3.0.3 on 2020-03-01 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torrents',
            name='type',
            field=models.CharField(choices=[('to', 'Torrent'), ('fi', 'Filme'), ('se', 'Serie'), ('ar', 'Arquivo'), ('jo', 'Jogo')], default=[('to', 'Torrent'), ('fi', 'Filme'), ('se', 'Serie'), ('ar', 'Arquivo'), ('jo', 'Jogo')], max_length=2),
        ),
    ]
