# Generated by Django 3.0.3 on 2020-03-01 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_auto_20200301_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torrents',
            name='type',
            field=models.CharField(choices=[('Torrent', 'Torrent'), ('Filme', 'Filme'), ('Serie', 'Serie'), ('Arquivo', 'Arquivo'), ('Jogo', 'Jogo')], default=[('Torrent', 'Torrent'), ('Filme', 'Filme'), ('Serie', 'Serie'), ('Arquivo', 'Arquivo'), ('Jogo', 'Jogo')], max_length=7),
        ),
    ]
